### ISSUE TITLE
New Request -- Additional parameter 

### ISSUE THREAD

**Issue by shekar3110a** [yogeshsd/query2report#11]
Hi There,
I really love the way you built the tool, i just need one small modification if possible ..
i.e Lets say i want to pass a XYZ as a variable in the Get/Post url and the same needs to be passed as one of the Variable for the SQL by replacing the string ..
Eg., I say in the quer where ABC = @@XYZ@@ and this XYZ will be passed as the URL get 123.com/q2r?XYZ=89898 
By doing this i can filter i can use the tool in a different way ..
do let me know if this possible on an urgent basis .. please
Best Regards
Shekar

**Comment by yogeshsd** [comment]
Hello Shekar,

The parameter map is actually being set as a JSON to the rest post request. 

Refer to the attached image. Will that suffice your usecase? or you are still looking for it to be sent as a query parameter?

Let me know. 

![parametermap](https://user-images.githubusercontent.com/17299986/53390263-9ea6ad80-39b8-11e9-97dd-6d131c5e1d91.png)


Thanks
Yogesh

**Comment by yogeshsd** [comment]
Hello Shekar,

Did you get a chance to review my response and let me know that suffices 

Thanks
Yogesh

**Comment by shekar3110a** [comment]
hi Yogesh 

let me check tomorrow and come back to you ..

Regards

Shekar

**Comment by shekar3110a** [comment]
Hi Yogesh
i tried to check the proposed model nut doesn't seems to it the usecase

basically what i have want as a end result is this;

 See i have a application portal which is working and I want kill the reporting module with in that application and redirect the user to q2r for all the canned reports …


the user is already logged in to the application and also user management also builtin witth that application so on the other had in the q2r i will build one user and create all the required reports in there and want auto login with that particular user and along with that i want to pass the Original user id into q2r as a global variable at the time of connecting to q2r and later want to use this variable to be integrated in the SQL to filter that data for that user.


hence i was asking that modification if possible ..


regards

Shekar

**Comment by yogeshsd** [comment]
Hello Shekar,

It is going to be little tricky as the URL for each element in the report is built in Query2Report code and that what you will be passing will be against the report URL.

Should think of how to propagate the parameters from report URL to report charts ( or elements ) url.

Once i get figure out a clean way of propagating the report URL level parameters , the down stream implementation would be easy.

Also, i believe between the you application and q2r you would be using a secret user with session time much higher?

and hopefully both the application run on the same server so that cookies are forwarded your application to q2r..

Give me couple of days, i will update you.

It will also be better to discuss the details on yogeshsd@gmail.com. Drop me a test email so that i can reply to that once i am done.

Thanks
Yogesh

**Comment by shekar3110a** [comment]
Hi Yogesh,

You already have my email and also on the changes my colleage naga was working on that, let me discuss with him as to how much he managed move forward on the required customisation and come back to you ..

Thank you very much for your quick support

Regards

shekar
